- name: Configure superset
  template:
    src: config.py.j2
    dest: "{{ superset_python_path }}/dist-packages/superset/config.py"
  notify:
    - restart superset

- name: Create superset systemd service
  template:
    src: "superset.service.j2"
    dest: "{{ superset_service }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemctl
    - restart superset

- name: Ensure Superset is running
  service:
    name: superset
    state: started
    enabled: yes
