- name: Configure superset
  template:
    src: config.py.j2
    dest: "{{ superset_python_path }}/dist-packages/superset/config.py"
  notify:
    - restart superset

- name: Create admin user
  become: yes
  become_user: superset
  shell: "fabmanager create-admin --app {{ superset_app }} --username {{ superset_username }} --firstname {{ superset_firstname }}  --lastname {{ superset_lastname }}  --email {{ superset_email }} --password {{ superset_password}}"

- name: Prepare superset DB
  become: yes
  become_user: superset
  shell: superset db upgrade

- name: Loading examples
  become: yes
  become_user: superset
  shell: superset load_examples
  when: superset_load_examples

- name: Init superset
  become: yes
  become_user: superset
  shell: superset init

- name: Create superset systemd service
  template:
    src: "superset.service.j2"
    dest: "{{ superset_service }}"
    owner: root
    group: root
    mode: 644
  notify:
    - reload systemctl
    - restart superset

- name: Ensure Superset is running
  service:
    name: superset
    state: started
    enabled: yes