---

- name: Install APT requirements
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - libsasl2-dev
      - libldap2-dev
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python-setuptools

#- name: Upgrade openSSL
#  command: "python -m easy_install --upgrade pyOpenSSL"
#  changed_when: false

- name: Install pip packages
  pip:
    name: "{{ pippkgs }}"
    executable: pip3
    state: present
  vars:
    pippkgs:
      - setuptools
      - cryptography
#      - werkzeug==0.16.1
      - psycopg2-binary
      - pyopenssl
      - pip
      - email_validator

#- name: self upgrade setuptools and pip
#  pip:
#    name: "{{ item }}"
#    executable: pip3
#    state: latest
#  with_items:
#    - setuptools
#    - pip
#    - email_validator

- name: Create user for superset
  user:
    name: "{{ superset_user }}"
    home: "{{ superset_path }}"
    shell: /bin/false

- name: Create superset group.
  group:
    name: "{{ superset_group }}"

- name: Install superset
  pip:
    name: apache-superset
    version: "{{ superset_version }}"
    executable: pip3
  register: superset_install
  notify:
    - Create admin user
    - Prepare superset DB
    - Load examples
    - Init superset
