---

- name: Create user for superset
  user:
    name: "{{ superset_user }}"
    home: "{{ superset_path }}"
    shell: /bin/bash

- name: Create superset group.
  group:
    name: "{{ superset_group }}"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: common.yml
