---

- name: Create user for superset
  user:
    name: "{{ superset_user }}"
    home: "{{ superset_path }}"
    shell: /bin/bash

- name: Create superset group.
  group:
    name: "{{ superset_group }}"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_role:
    name: geerlingguy.redis
  when: enable_superset_redis

#- include_role:
#    name: geerlingguy.postgresql
#  when: enable_superset_local_postgres

- include: common.yml

- include: nginx.yml
  when: enable_superset_nginx
