- name: reload systemctl
  command: systemctl daemon-reload

- name: restart superset
  service:
    name: superset
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: superset
    state: restarted
    enabled: yes